version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: firebase
    versions:
    - 8.3.2
    - 8.3.3
    - 8.4.1
  - dependency-name: redux
    versions:
    - 4.0.5
  - dependency-name: react-redux
    versions:
    - 7.2.3
  - dependency-name: mime
    versions:
    - 1.4.1
  - dependency-name: extend
    versions:
    - 3.0.2
  - dependency-name: fresh
    versions:
    - 0.5.2
  - dependency-name: hoek
    versions:
    - 4.2.1
  - dependency-name: forwarded
    versions:
    - 0.1.2
